# Generated by Django 5.1.6 on 2025-02-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartweb', '0002_journal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
