# Generated by Django 5.1.6 on 2025-02-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartweb', '0003_journal_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
