apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      containers:
        - name: {{ .Values.appName }}-{{ randAlpha 5 | lower }}
          image: {{ .Values.imageName }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
